/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiEmailWebhookRouteImport } from './routes/api/email/webhook'
import { Route as ApiEmailProcessRouteImport } from './routes/api/email/process'
import { Route as ApiEmailPreviewRouteImport } from './routes/api/email/preview'
import { Route as ApiPublicHooksProcessNotificationsRouteImport } from './routes/api/public/hooks/process-notifications'
import { Route as ApiPublicHooksPredictCrisisRouteImport } from './routes/api/public/hooks/predict-crisis'
import { Route as ApiPublicHooksBroadcastProductUpdateRouteImport } from './routes/api/public/hooks/broadcast-product-update'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailWebhookRoute = ApiEmailWebhookRouteImport.update({
  id: '/api/email/webhook',
  path: '/api/email/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailProcessRoute = ApiEmailProcessRouteImport.update({
  id: '/api/email/process',
  path: '/api/email/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailPreviewRoute = ApiEmailPreviewRouteImport.update({
  id: '/api/email/preview',
  path: '/api/email/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProcessNotificationsRoute =
  ApiPublicHooksProcessNotificationsRouteImport.update({
    id: '/api/public/hooks/process-notifications',
    path: '/api/public/hooks/process-notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPredictCrisisRoute =
  ApiPublicHooksPredictCrisisRouteImport.update({
    id: '/api/public/hooks/predict-crisis',
    path: '/api/public/hooks/predict-crisis',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBroadcastProductUpdateRoute =
  ApiPublicHooksBroadcastProductUpdateRouteImport.update({
    id: '/api/public/hooks/broadcast-product-update',
    path: '/api/public/hooks/broadcast-product-update',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/email/preview': typeof ApiEmailPreviewRoute
  '/api/email/process': typeof ApiEmailProcessRoute
  '/api/email/webhook': typeof ApiEmailWebhookRoute
  '/api/public/hooks/broadcast-product-update': typeof ApiPublicHooksBroadcastProductUpdateRoute
  '/api/public/hooks/predict-crisis': typeof ApiPublicHooksPredictCrisisRoute
  '/api/public/hooks/process-notifications': typeof ApiPublicHooksProcessNotificationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/email/preview': typeof ApiEmailPreviewRoute
  '/api/email/process': typeof ApiEmailProcessRoute
  '/api/email/webhook': typeof ApiEmailWebhookRoute
  '/api/public/hooks/broadcast-product-update': typeof ApiPublicHooksBroadcastProductUpdateRoute
  '/api/public/hooks/predict-crisis': typeof ApiPublicHooksPredictCrisisRoute
  '/api/public/hooks/process-notifications': typeof ApiPublicHooksProcessNotificationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/email/preview': typeof ApiEmailPreviewRoute
  '/api/email/process': typeof ApiEmailProcessRoute
  '/api/email/webhook': typeof ApiEmailWebhookRoute
  '/api/public/hooks/broadcast-product-update': typeof ApiPublicHooksBroadcastProductUpdateRoute
  '/api/public/hooks/predict-crisis': typeof ApiPublicHooksPredictCrisisRoute
  '/api/public/hooks/process-notifications': typeof ApiPublicHooksProcessNotificationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/api/email/preview'
    | '/api/email/process'
    | '/api/email/webhook'
    | '/api/public/hooks/broadcast-product-update'
    | '/api/public/hooks/predict-crisis'
    | '/api/public/hooks/process-notifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/api/email/preview'
    | '/api/email/process'
    | '/api/email/webhook'
    | '/api/public/hooks/broadcast-product-update'
    | '/api/public/hooks/predict-crisis'
    | '/api/public/hooks/process-notifications'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/api/email/preview'
    | '/api/email/process'
    | '/api/email/webhook'
    | '/api/public/hooks/broadcast-product-update'
    | '/api/public/hooks/predict-crisis'
    | '/api/public/hooks/process-notifications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApiEmailPreviewRoute: typeof ApiEmailPreviewRoute
  ApiEmailProcessRoute: typeof ApiEmailProcessRoute
  ApiEmailWebhookRoute: typeof ApiEmailWebhookRoute
  ApiPublicHooksBroadcastProductUpdateRoute: typeof ApiPublicHooksBroadcastProductUpdateRoute
  ApiPublicHooksPredictCrisisRoute: typeof ApiPublicHooksPredictCrisisRoute
  ApiPublicHooksProcessNotificationsRoute: typeof ApiPublicHooksProcessNotificationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/webhook': {
      id: '/api/email/webhook'
      path: '/api/email/webhook'
      fullPath: '/api/email/webhook'
      preLoaderRoute: typeof ApiEmailWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/process': {
      id: '/api/email/process'
      path: '/api/email/process'
      fullPath: '/api/email/process'
      preLoaderRoute: typeof ApiEmailProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/preview': {
      id: '/api/email/preview'
      path: '/api/email/preview'
      fullPath: '/api/email/preview'
      preLoaderRoute: typeof ApiEmailPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-notifications': {
      id: '/api/public/hooks/process-notifications'
      path: '/api/public/hooks/process-notifications'
      fullPath: '/api/public/hooks/process-notifications'
      preLoaderRoute: typeof ApiPublicHooksProcessNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/predict-crisis': {
      id: '/api/public/hooks/predict-crisis'
      path: '/api/public/hooks/predict-crisis'
      fullPath: '/api/public/hooks/predict-crisis'
      preLoaderRoute: typeof ApiPublicHooksPredictCrisisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/broadcast-product-update': {
      id: '/api/public/hooks/broadcast-product-update'
      path: '/api/public/hooks/broadcast-product-update'
      fullPath: '/api/public/hooks/broadcast-product-update'
      preLoaderRoute: typeof ApiPublicHooksBroadcastProductUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiEmailPreviewRoute: ApiEmailPreviewRoute,
  ApiEmailProcessRoute: ApiEmailProcessRoute,
  ApiEmailWebhookRoute: ApiEmailWebhookRoute,
  ApiPublicHooksBroadcastProductUpdateRoute:
    ApiPublicHooksBroadcastProductUpdateRoute,
  ApiPublicHooksPredictCrisisRoute: ApiPublicHooksPredictCrisisRoute,
  ApiPublicHooksProcessNotificationsRoute:
    ApiPublicHooksProcessNotificationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
